//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;


namespace cfg
{ 
   
public sealed partial class Tables
{
    public ConfigWorldContainer ConfigWorldContainer {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        ConfigWorldContainer = new ConfigWorldContainer(loader("configworldcontainer")); 
        tables.Add("ConfigWorldContainer", ConfigWorldContainer);
        PostInit();

        ConfigWorldContainer.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        ConfigWorldContainer.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}