// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies";
    extern const char* const UnityCopyright = "(c) 2005-2023 Unity Technologies. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/build/output/unity/unity";

    extern const char* const UnityVersion = "2021.3.24f1";
    extern const char* const UnityVersionDigits = "2021.3.24";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2021;
    extern const UInt32 UnityVersionMajor = 3;
    extern const UInt32 UnityVersionMinor = 24;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2021.3.24f1_cf10dcf7010d";
    extern const char* const UnityVersionUnderHash_Verbose = "2021.3.24f1_cf10dcf7010d";
    extern const char* const UnityVersionUnderHash_WithParens = "2021.3.24f1 (cf10dcf7010d)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 13570268;

    extern const UInt64 UnityVersionDate = 1681869477;
    extern const char* const UnityVersionBranch = "2021.3/staging";
    extern const char* const UnityVersionDisplay = "2021.3.24f1";
    extern const char* const UnityVersionDisplay_Verbose = "2021.3.24f1.git.13570268";
    extern const char* const UnityVersionRevision = "cf10dcf7010d";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2021.3.24f1 (cf10dcf7010d)";
    extern const wchar_t* const L_UnityVersion = L"2021.3.24f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies"
    #define UNITY_COPYRIGHT "(c) 2005-2023 Unity Technologies. All rights reserved."
    #define UNITY_VERSION_VER 2021
    #define UNITY_VERSION_MAJ 3
    #define UNITY_VERSION_MIN 24
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2021.3.24f1_cf10dcf7010d"
    #define UNITY_VERSION_PARENS_HASH "2021.3.24f1 (cf10dcf7010d)"
    #define UNITY_VERSION_BLD 13570268
    #define UNITY_VERSION_WIN "2021.3.24.13570268"

#endif // !RC_INVOKED
